first brew upgrade python and ignore fails

diff --git a/github-actions/install-dep-gnuplot/action.yml b/github-actions/install-dep-gnuplot/action.yml
--- a/github-actions/install-dep-gnuplot/action.yml
+++ b/github-actions/install-dep-gnuplot/action.yml
@@ -15,6 +15,8 @@ runs:
       run: |
           if ${{ toJSON( runner.os == 'macOS' ) }}; then
             echo "::group::Install gnuplot (via brew)"
+            brew update
+            brew upgrade python || true # currently (2024-03-25) 3.12 link fails
             HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install gnuplot
             echo "::endgroup::"
           fi
